---
title: "Affordable Housing Analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(sf)
```
Lets read in all of the data provided to see what will be useful. 
```{r}
property_details <- read.csv(file = "../Data/property_details.csv")
LIHTC <- read.csv(file = "../Data/LIHTC.csv")
full_sales <- read.csv(file = "../Data/full_sales.csv")
filtered_sales <- read.csv(file = "../Data/filtered_sales.csv")
barnes <- read.csv(file = "../Data/barnes.csv")
asssesments <- read.csv(file = "../Data/assessments.csv")
```

We need to split the latitude and longitude of the property_details data frame and add them back to the original data frame as new columns. 
```{r}
split_coord <- str_split(str_extract(string = property_details$centroid,pattern =  "(?<=\\().*?(?=\\))"),",", simplify = TRUE)
property_lat_long <- rename(as_tibble(split_coord), LAT = V1, LONG = V2)
property_details$LAT <- property_lat_long$LAT
property_details$LONG <- property_lat_long$LONG
```


Get point geometries for the properties and the LIH areas. 
```{r}
property_details_sf <- st_as_sf(property_details, coords = c("LAT", "LONG"), crs = 4326, agr = "constant")
LIHTC_sf <- st_as_sf(LIHTC, coords = c("LATITUDE", "LONGITUDE"), crs = 4326, agr = "constant")
```

```{r}

```

